### ISSUE TITLE
[Feature request] - Add public API Endpoints

### ISSUE THREAD

**Issue by serotonie** [timdlp/geoinfHutFinder#8]
Hi,
Could you add some API Endpoints to be able to integrate to kadas ?
Histoire qu'on arrête de perdre du temps à chaque SAT/RAU à refaire une carte de toute la Suisse avec toutes les cabanes possibles ! :D

**Comment by timdlp** [comment]
Hi @serotonie,

Unfortunately this is a school project done back in 2017. The original ZIP file with the cabanes doesn't seem to be available online anymore and the database/server provided by HEIG-VD must have been shut down long ago.

I don't know about any GIS that provides endpoints for `cabanes` but maybe you could try to get in touch with somebody at the https://www.sac-cas.ch/ - They might be able to provide with an up-to-date list of the cabanes in Switzerland. 

Unfortunately I don't have the ressources to host such an API but I would be happy to help you spin up such a service. 

Regards

Tim'

**Comment by serotonie** [comment]
Merci pour le sérieux de ta réponse à ma requête à peine ironique :)
On se croise en service

**Comment by timdlp** [comment]
Léo?

**Comment by serotonie** [comment]
Yep ☺️ tu me raconteras l'OSINT nécessaire, même si ça devait pas être très compliqué.
